### ISSUE TITLE
SSL connections don't work (anymore?)

### ISSUE THREAD

**Issue by olebole** [hkoba/tkhtml3#4]
Hi,

I am the owner of the base tkhtml3 repository and the maintainer of its Debian package; however I have not much experience in tcl. Therefore I'd like to get your expertise here.

The Debian package of tkhtml3/hv3 just received a bug report [#952581](https://bugs.debian.org/952581) that shows that hv3 doesn't work with https. `hv3 https://www.debian.org` gives the following stacktrace:
```
wrong # args: should be "::hv3::protocol::SSocket host port"
wrong # args: should be "::hv3::protocol::SSocket host port"
    while executing
"::hv3::protocol::SSocket -async www.debian.org 443"
    ("eval" body line 1)
    invoked from within
"eval $defcmd $sockopts $targetAddr"
    invoked from within
"::http::geturl https://www.debian.org -command {::hv3::protocol::inst1 _DownloadCallback ::hv3::request::inst1} -handler {::hv3::protocol::inst1 _Appe..."
    ("eval" body line 1)
    invoked from within
"eval $geturl"
    (procedure "request_http" line 76)
    invoked from within
"request_http ::hv3::protocol::inst1 ::hv3::request::inst1"
    (in namespace eval "::hv3::protocol" script line 1)
    invoked from within
"namespace eval ::hv3::protocol $m ::hv3::protocol::inst1 $args"
    (procedure "::hv3::protocol::inst1" line 1)
    invoked from within
"$me request_http $downloadHandle"
    (procedure "SSocketReady" line 18)
    invoked from within
"SSocketReady ::hv3::protocol::inst1 sock56114c0b0ab0 ::hv3::request::inst1"
    (in namespace eval "::hv3::protocol" script line 1)
    invoked from within
"namespace eval ::hv3::protocol $m ::hv3::protocol::inst1 $args"
    (procedure "::hv3::protocol::inst1" line 1)
    invoked from within
"::hv3::protocol::inst1 SSocketReady sock56114c0b0ab0 ::hv3::request::inst1"
```
I have no idea how to fix it. I would tend to let the Debian package die; however if you would have an idea, I could try to apply a fix.

**Comment by hkoba** [comment]
Hi!

I'm glad to hear someone is still interested in Dan's tkhtml3&hv3.
Actually, I'm not actively maintaining hv3. I can't promise I can fix it
but I will try it. Can you wait a week?


2020年2月26日(水) 21:17 Ole Streicher <notifications@github.com>:

**Comment by olebole** [comment]
Sure, the problem seems already to exist quite some time, so one week doesn't matter ;-)

BTW, the code is quite popular on Debian -- our [voluntary popularity counter](https://qa.debian.org/popcon.php?package=tk-html3) (opt-in at installation time) has ~3600 installations and ~300 regular users.

Since you made some more changes with respect to my repository: do you think they are worth to include as well? Also, maybe I should put you as the "official upstream" into the Debian package?

**Comment by hkoba** [comment]
I'm not sure the above patch is perfect, but it seems to me it worked to browse https://www.debian.org/.

> BTW, the code is quite popular on Debian -- our [voluntary popularity counter](https://qa.debian.org/popcon.php?package=tk-html3) (opt-in at installation time) has ~3600 installations and ~300 regular users.
> 
> Since you made some more changes with respect to my repository: do you think they are worth to include as well? Also, maybe I should put you as the "official upstream" into the Debian package?

Thank you for saying that. It's my honor. Including my changes are ok of course. But, for about becoming an "official upstream", ... won't Dan feel bad?

**Comment by olebole** [comment]
I tried it, but I got the error message

> # Bad Request
>
>Your browser sent a request that this server could not understand. Reason: You're speaking plain >HTTP to an SSL-enabled server port. Instead use the HTTPS scheme to access this URL, please.
>
> -----
> *Apache Server at www.debian.org Port 80*

**Comment by hkoba** [comment]
Hv3 uses [tcltls](https://core.tcl-lang.org/tcltls/index) to support SSL/TLS, like most other Tcl scripts.
Please test below:

```console
% echo package require tls | tclsh
```

If the above shows error like `can't find package tls`, you must install it first.

I think it is better to add .deb level dependency.
https://packages.debian.org/buster/tcl-tls

**Comment by hkoba** [comment]
Oh, sorry. I just found the cause of Bad Request was the lack of hv3_polipo, not tcltls.
(Lack of tcltls shows another error).

To get hv3_polipo, see http://tkhtml.tcl.tk/ffaq.html#hv3_polipo

**Comment by olebole** [comment]
tcl-tls is installed (and will be usually installed on Debian since it is set to "recommended": these packages are by default installed).
(`hv3_`)`polipo` is however a problem here: It is not in Debian anymore, and as an unmaintained package, there is no real chance to get it back.
I also do not see why it is needed -- at least the source code shows that it was also thought to work without, https://github.com/hkoba/tkhtml3/blob/32f931ae2fef391e99048d106706dcaa904b9f79/hv/hv3_http.tcl#L292-L302

IMO there is just the `socket` line above should be replaces by a call to `::tls::socket`, as shown [in this example](https://wiki.tcl-lang.org/page/tls):

```
package require tls 1.6.7
proc tls:socket args {
    set opts [lrange $args 0 end-2]
    set host [lindex $args end-1]
    set port [lindex $args end]

    # […]
    ::tls::socket -servername $host {*}$opts $host $port

    #[…]
}

# using the http package also needs this:
package require http
http::register https 443 tls:socket
```
However, I don't know exactly how TLS works, and also not good in tcl.

**Comment by hkoba** [comment]
Hi,

> (`hv3_`)`polipo` is however a problem here: It is not in Debian anymore, and as an unmaintained package, there is no real chance to get it back.
> I also do not see why it is needed -- at least the source code shows that it was also thought to work without,
> 

You may be curious about why hv3_polipo is introduced. If I recall correctly, it was primarily introduced for the entire responsiveness of hv3, and later also helped to provide some kind of workaround such as `<meta charset>` related reloading for encoding changes. (Unfortunately, I can't dig out exact conversations from my mbox. It might be on cvstrac tickets.)

But anyway, dropping an unmaintained package from the distribution seems fair enough for me, so I agree with removing the use of hv3_polipo from your Debian package.

As for my repository github.com/hkoba/tkhtml3, I will try to keep hv3 mostly as-is. Because my main interest is understanding how to use tkhtml3 and the hv3 code is the most important source of knowledge from the original author.
